export type EnvConfig = {
    CLIENT?: string;
    USER: string;
    PASSWORD: string;
    HOST: string;
    PORT: number;
    DATABASE: string;
    APP_NAME?: string;
    IDLE_IN_TRANSACTION_TIMEOUT?: number;
    SSL_REJECT_UNAUTHORIZED?: boolean;
    SSL_CA?: string;
    SSL_CERT?: string;
    SSL_KEY?: string;
    MAX_POOL_SIZE?: number;
    MIN_POOL_SIZE?: number;
    ACQUIRE_CONNECTION_TIMEOUT?: number;
    MIGRATIONS_TABLE_SCHEMA?: string;
    MIGRATIONS_DIR: string;
    SEARCH_PATH?: string[];
};
